export enum FieldName {
  cvv = 'cvv',
  cardYear = 'card_year',
  cardMonth = 'card_month',
  cardNumber = 'card_number',
  cardHolderName = 'cardholdername',
  cpfNumber = 'cpf_number',
  cpfName = 'cpf_name',
  birthDate = 'birth_date',
  street = 'street',
  address1 = 'address',
  address2 = 'address2',
  streetNumber = 'street_number',
  apt = 'apt',
  city = 'city',
  zip = 'zip',
  state = 'state',
  installments = 'installments',
  phone = 'phone',
}
